.github/workflows/npm-publish-package.yml
README.md

Create a workflow (action) to build and publish the package in NPM when GitHub release is updated.

publish package workflow

---

package-lock.json
package.json

The goal is to add a dev build command that triggers on change in files and folders.
re #25

feat: add dev command

---

utils/generateIndex.ts

fix: generated main file formatting

---

package.json

refactor: update information, keywords & GH url

---

README.md
index.ts
tsconfig.json
utils/generateReadme.ts

63 omit the extension and import file ts error

---

package.json

refactor: add contributors field

---

index.ts
utils/generateReadme.ts
utils/renderEslint.ts

ESLint + Prettier + Husky added by default
Switch End2End tools order - Playwright is first option, Cypress is last
re #81

feat: ESLint + Prettier + Husky added by default; Switch End2End order

---

template/base/.vscode/extensions.json
template/base/.vscode/settings.json
template/base/jsconfig.json

* add .vscode/settings.json
* add .vscode/extensions.json
* add jsconfig.json

.vscode default settings & extensions

---

package-lock.json
package.json
utils/renderEslint.ts

Bump package version to `0.2.0`

119 prettier is missing

---

.github/workflows/npm-publish-package.yml
README.md
__test__/getCommand.spec.ts
__test__/locale.spec.ts
__test__/sortDependencies.spec.ts
package-lock.json
package.json
vitest.config.ts

feat: add unit tests using vitest

---

utils/renderEslint.ts

fix: add cypress support folder to eslint overrides

---

utils/getLanguage.ts

fix: prioritize enviornment variables over Intl.DateTimeFormat

---

.github/pull_request_template.md

feat(pull_request): create Pull request template

---

package-lock.json
template/base/src/components/README.md

Create a README.md file in components folder describing **Component Recommended Rules**
re #204

Create components README.md

---

template/base/package.json
template/base/vite.config.js.data.mjs

1. Update base project setup. 
2. Add devtools package in package.json
3. Update vite.config.js (import package & init devtools)
re #183
Built project

feat: add vite devtools plugin

---

utils/getLanguage.ts

When users configure LANG related information by themselves, irregular spelling or capitalization problems may occur.
https://github.com/vuejs/create-vue/commit/2195946f76832710c4fceb47c64e6c747cbed83d

feat: use Intl.getCanonicalLocales check locale

---

utils/generateReadme.ts

Fix README.md generated content for Nightwatch component testing
https://github.com/vuejs/create-vue/pull/448

fix: NW component testing condition

---

index.ts

fix: get correct flags

---

.github/workflows/ci.yml
scripts/snapshot.mjs

Remove TS and Vitest feature flags as they are now part of the default bundle

ci: remove ts and vitest feature flags

---

index.ts
scripts/snapshot.mjs
template/base/.vscode/settings.json
template/config/eslint/.vscode/extensions.json
template/config/eslint/.vscode/settings.json
utils/renderEslint.ts
utils/renderTemplate.ts

re https://github.com/vuejs/create-vue/pull/467

feat: feat-eslint-vscode-settings

---

index.ts

bun package manager support
re https://github.com/vuejs/create-vue/pull/471

fix: command description for bun

---

template/base/vite.config.js.ejs
template/code/default/src/components/HelloWorld.vue
template/code/default/src/components/TheWelcome.vue
template/code/router/src/components/HelloWorld.vue
template/code/router/src/components/TheWelcome.vue
template/code/typescript-default/src/components/HelloWorld.vue
template/code/typescript-default/src/components/TheWelcome.vue
template/code/typescript-router/src/components/HelloWorld.vue
template/code/typescript-router/src/components/TheWelcome.vue
template/exam-project/vite.config.ts
utils/generateReadme.ts

feat: update vite url
